"""Does error COMPOUND up the ladder? One, two and three lifts to the same point.

The u1 half of a test pair; the u2 half is `u2_2d/scripts/45_multi_lift_-
compounding.py`. Both studies should carry the same tests even where they give
different answers, and this one had no counterpart in either until now.

WHAT IS AND IS NOT ALREADY MEASURED. The deployed pipeline is a multi-lift
ladder and stage 04 validates its endpoint, but every controlled measurement of
the lift itself -- `59_pre_post_retherm.py`, the generalization study, the
appendix scans -- uses a SINGLE lift from an HMC coarse ensemble. So "how much
of the endpoint's error was injected by the last lift and how much accumulated
climbing to it" has never been isolated. It matters because the ladder's whole
premise is to start where sampling works and climb, which makes the rung count
the one cost the method cannot avoid.

THE DESIGN. Fix the ENDPOINT and vary the number of lifts, so the arms differ in
nothing else:

    3 lifts   L=8  ->  L=16  ->  L=32  ->  L=64
    2 lifts            L=16  ->  L=32  ->  L=64
    1 lift                      L=32  ->  L=64

Every arm's starting ensemble is generated by HMC at exactly the chain's
coupling for that rung, with `topological_updates=True` so it is not
sector-frozen. Two things this guards against, both of which bit the u2 run:
reading the nearest ensemble off disk instead (a few percent in beta moves the
observables by more than the effect being measured), and starting from a
topologically frozen configuration (which would make the arms differ in sector
content, and would make the charge-preservation check vacuous).

TWO VARIANTS, and their contrast is the actual result. `--intermediate-retherm 0`
is pure model composition; the default 10 is what the deployed ladder does. If
the tail resets the error between rungs the variants separate and the ladder is
safe to lengthen; if not, error compounds and rung count is a real cost.

ERRORS ARE tau_int-AWARE, as everywhere else in u1 (NARRATIVE 25.7 / M4): the
configurations come from a small number of chains and a naive across-
configuration SEM would be optimistic. That also makes the z here directly
comparable with `59_pre_post_retherm.py`.

    python u1_2d/scripts/60_multi_lift_compounding.py --device cpu
"""
from __future__ import annotations

import argparse
import math
import sys
import time
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from u1_2d.lgt import make_action, run_hmc_ensemble
from u1_2d.lgt.blocking import approx_matched_fine_beta
from u1_2d.lgt.exact import (topological_susceptibility_exact,
                             wilson_loop_exact)
from u1_2d.lgt.hmc import adapted_hmc_params
from u1_2d.lgt.lattice import (plaquette_angles, topological_charge,
                               wilson_loop_angles)
from u1_2d.lgt.local_updates import retherm_sweeps
from u1_2d.model.train import load_checkpoint
from u1_2d.pipeline.ladder import generate_fine_from_coarse
from u1_2d.utils import save_json, set_seed
from u1_2d.validate.stats import autocorr_aware_mean_err

LOOPS = [(1, 1), (2, 2), (4, 4)]


def loop_means(field: torch.Tensor) -> dict:
    out = {}
    with torch.no_grad():
        for nx, ny in LOOPS:
            ang = (plaquette_angles(field) if (nx, ny) == (1, 1)
                   else wilson_loop_angles(field, nx, ny))
            out[f"W{nx}x{ny}"] = torch.cos(ang).mean(dim=(-2, -1)).cpu().numpy()
    return out


def score(field, beta, size, n_chains):
    stats = loop_means(field)
    out = {}
    for (nx, ny) in LOOPS:
        key = f"W{nx}x{ny}"
        v = np.asarray(stats[key], dtype=float)
        exact = wilson_loop_exact(beta, nx * ny, "wilson", size)
        mean, err, tau = autocorr_aware_mean_err(v, n_chains)
        bias = mean - exact
        out[f"z_{key}"] = float(bias / max(err, 1e-15))
        out[f"ppm_{key}"] = float(1e6 * bias / exact)
        out[f"tau_{key}"] = float(tau)
    with torch.no_grad():
        q = topological_charge(field).cpu().numpy().astype(float)
    out["q_squared"] = float((q ** 2).mean())
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--checkpoint", default="out/u1_2d/checkpoints/score_net.pt")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--start-size", type=int, default=8)
    ap.add_argument("--start-beta", type=float, default=1.75)
    ap.add_argument("--n-lifts", type=int, default=3)
    ap.add_argument("--n-configs", type=int, default=128)
    ap.add_argument("--n-chains", type=int, default=16)
    ap.add_argument("--burn-in", type=int, default=800)
    ap.add_argument("--thin", type=int, default=5)
    ap.add_argument("--sampler-steps", type=int, default=200)
    ap.add_argument("--intermediate-retherm", type=int, default=10)
    ap.add_argument("--final-retherm", type=int, default=10)
    ap.add_argument("--seed", type=int, default=3131)
    ap.add_argument("--out-dir", default="out/u1_2d/multi_lift")
    args = ap.parse_args()

    device = args.device
    set_seed(args.seed)
    model, schedule = load_checkpoint(args.checkpoint, device)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    rungs = [(args.start_size, args.start_beta)]
    for _ in range(args.n_lifts):
        L, b = rungs[-1]
        rungs.append((L * 2, approx_matched_fine_beta(b, "wilson")))
    print("chain:")
    for L, b in rungs:
        chi = topological_susceptibility_exact(b, "wilson")
        print(f"  L={L:3d}  beta={b:10.4f}   exact <Q^2> = {chi * L * L:7.4f}")
    final_size, final_beta = rungs[-1]

    results = []
    for k in range(1, args.n_lifts + 1):
        start_size, start_beta = rungs[args.n_lifts - k]
        print(f"\n{'='*74}\n{k} LIFT(S): start L={start_size} "
              f"beta={start_beta:.4f}  ->  L={final_size} beta={final_beta:.3f}")
        t0 = time.time()

        cache = out / f"hmc_L{start_size}_beta{start_beta:.4f}_topo.pt"
        if cache.exists():
            field = torch.load(cache, map_location="cpu")["field"]
            print(f"  start: cached {cache.name}")
        else:
            action_c = make_action("wilson", start_beta)
            step, n_steps = adapted_hmc_params(start_beta)
            field, _ = run_hmc_ensemble(
                start_size, action_c, n_configs=args.n_configs,
                n_chains=args.n_chains, burn_in=args.burn_in, thin=args.thin,
                step_size=step, n_steps=n_steps, device=device,
                topological_updates=True)
            field = field.cpu()
            torch.save({"field": field}, cache)
            print(f"  start: HMC [{time.time()-t0:.0f}s]")

        q_start = topological_charge(field).cpu().numpy()
        base = score(field, start_beta, start_size, args.n_chains)
        qsq_exact = (topological_susceptibility_exact(start_beta, "wilson")
                     * start_size ** 2)
        print(f"  start: z(plaq)={base['z_W1x1']:+7.2f}   "
              f"<Q^2>={base['q_squared']:.4f} (exact {qsq_exact:.4f})")
        if base["q_squared"] < 0.25 * qsq_exact:
            print("  WARNING: start is sector-frozen; arms would differ in")
            print("  topology as well as in lift count. Do not read the result.")

        set_seed(args.seed)
        per_rung = []
        for j in range(k):
            nb = rungs[args.n_lifts - k + j + 1][1]
            ns = rungs[args.n_lifts - k + j + 1][0]
            field = generate_fine_from_coarse(
                model, schedule, field.cpu(), nb, device=device,
                n_sampler_steps=args.sampler_steps, n_corrector_steps=1,
                batch_size=64, consistency_weight=1.0)
            raw = score(field, nb, ns, args.n_chains)
            if args.intermediate_retherm and j < k - 1:
                field = retherm_sweeps(field, make_action("wilson", nb),
                                       args.intermediate_retherm)
            per_rung.append({"lattice_size": ns, "beta": nb, "raw": raw})
            print(f"    rung {j+1}: L={ns:3d} beta={nb:9.3f}  z = "
                  f"{raw['z_W1x1']:+8.2f} / {raw['z_W2x2']:+7.2f} / "
                  f"{raw['z_W4x4']:+7.2f}   <Q^2>={raw['q_squared']:.4f}")

        final_raw = score(field, final_beta, final_size, args.n_chains)
        post = score(retherm_sweeps(field, make_action("wilson", final_beta),
                                    args.final_retherm),
                     final_beta, final_size, args.n_chains)
        q_end = topological_charge(field).cpu().numpy()
        match = float((q_end == q_start).mean())
        print(f"  FINAL raw  z = {final_raw['z_W1x1']:+8.2f} / "
              f"{final_raw['z_W2x2']:+7.2f} / {final_raw['z_W4x4']:+7.2f}")
        print(f"  FINAL +{args.final_retherm} z = {post['z_W1x1']:+8.2f} / "
              f"{post['z_W2x2']:+7.2f} / {post['z_W4x4']:+7.2f}")
        print(f"  charge preserved through {k} lift(s): {100*match:.1f}%")
        results.append({"n_lifts": k, "start_size": start_size,
                        "start_beta": start_beta, "start_score": base,
                        "per_rung": per_rung, "final_raw": final_raw,
                        "final_post": post, "charge_match_fraction": match,
                        "seconds": time.time() - t0})
        save_json(out / f"multi_lift_r{args.intermediate_retherm}.json",
                  {"chain": [{"lattice_size": L, "beta": b} for L, b in rungs],
                   "intermediate_retherm": args.intermediate_retherm,
                   "n_configs": args.n_configs, "n_chains": args.n_chains,
                   "arms": results})

    print(f"\n{'='*74}\nCOMPOUNDING at L={final_size}, beta={final_beta:.3f}, "
          f"intermediate retherm = {args.intermediate_retherm}")
    print(f"  {'lifts':>5s} {'|z| raw W1x1':>13s} {'|z| raw W2x2':>13s} "
          f"{'|z| post W1x1':>14s} {'ppm raw W1x1':>13s} {'Q kept':>8s}")
    for r in results:
        print(f"  {r['n_lifts']:5d} {abs(r['final_raw']['z_W1x1']):13.2f} "
              f"{abs(r['final_raw']['z_W2x2']):13.2f} "
              f"{abs(r['final_post']['z_W1x1']):14.2f} "
              f"{r['final_raw']['ppm_W1x1']:13.1f} "
              f"{100*r['charge_match_fraction']:7.1f}%")

    z1 = abs(results[0]["final_raw"]["z_W1x1"])
    zk = abs(results[-1]["final_raw"]["z_W1x1"])
    print()
    if zk > 2.0 * z1:
        print(f"  ERROR COMPOUNDS: {len(results)} lifts is "
              f"{zk/max(z1,1e-9):.1f}x worse than 1 at the same endpoint.")
    elif zk < 0.5 * z1:
        print(f"  The LONGER ladder is BETTER ({z1/max(zk,1e-9):.1f}x) -- not a")
        print("  compounding effect; check each arm's intermediate couplings")
        print("  against the training rungs before reading anything into it.")
    else:
        print(f"  NO COMPOUNDING within resolution: {len(results)} lifts sits at "
              f"{zk/max(z1,1e-9):.2f}x the 1-lift error.")
    print(f"\nwrote {out / f'multi_lift_r{args.intermediate_retherm}.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
