"""Does error COMPOUND up the ladder? One, two and three lifts to the same point.

WHAT IS AND IS NOT ALREADY MEASURED. The deployed pipeline is a multi-lift
ladder -- L = 8 at beta = 3.5 up to L = 64 at beta = 416.5, three lifts -- and
stage 04 validates the endpoint. But every controlled measurement of the lift
itself (`43_observable_scan.py`, `44_sweeps_vs_trajectories.py`, the crossover
scans) uses a SINGLE lift from an HMC coarse ensemble. So the question "how much
of the endpoint's error was injected by the last lift and how much accumulated
on the way" has never been isolated. It matters because the whole point of the
ladder is to start where sampling works and climb, so the number of rungs is the
one parameter the method cannot avoid paying for.

THE DESIGN. Fix the ENDPOINT and vary the number of lifts. A chain of rungs is
built from a starting (L, beta) by `topology_matched_fine_beta`, and three arms
converge on the same final rung:

    3 lifts   L=8  ->  L=16  ->  L=32  ->  L=64
    2 lifts            L=16  ->  L=32  ->  L=64
    1 lift                      L=32  ->  L=64

Each arm's own starting ensemble is generated by HMC at exactly the chain's
coupling for that rung -- not read from the nearest available file, because a
3% mismatch in beta would confound the very effect being measured. All three
arms therefore differ ONLY in how many times the model was applied.

TWO VARIANTS, and the contrast is the actual result. With `--no-intermediate-
retherm` the arms are pure model composition; with retherm between rungs (the
default, and what the deployed ladder does) each lift starts from a locally
equilibrated configuration. If the tail resets the error, the two variants
separate and the ladder is safe to lengthen. If they do not separate, error
compounds and the number of rungs is a real cost.

TOPOLOGY IS THE THIRD THING MEASURED, and it is a stronger test than the
single-lift one. Transport is exact per lift (`36_transport_check.py`), so after
three lifts EVERY fine configuration should still carry the charge of its L = 8
ancestor. That is checked configuration by configuration, not on averages.

    python u2_2d/scripts/45_multi_lift_compounding.py --device cuda
"""
from __future__ import annotations

import argparse
import math
import sys
import time
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from u2_2d.lgt.actions import WilsonU2Action
from u2_2d.lgt.blocking import topology_matched_fine_beta
from u2_2d.lgt.exact import plaquette_exact, wilson_loop_exact
from u2_2d.lgt.hmc import BatchedHMCU2, adapted_hmc_params
from u2_2d.lgt.lattice import (half_retr, plaquette, topological_charge,
                               wilson_loop)
from u2_2d.lgt.local_updates import retherm_sweeps
from u2_2d.model.det_lift import load_det_model, model_beta
from u2_2d.pipeline.ladder import generate_fine_from_coarse
from u2_2d.utils import (configure_device, load_ensemble, resolve_device,
                         save_json, set_seed)

LOOPS = [(1, 1), (2, 2), (4, 4)]


def score(links, beta, size):
    """Scores, AND the per-configuration values they were computed from.

    The per-config arrays are kept (`per_config`, written into the result
    JSON) so an error-bar method can be changed later -- a config-level
    bootstrap, a different resampling unit -- without redoing the lift on a
    GPU. Only summary z/ppm were saved originally, which made exactly that
    re-analysis impossible and forced a full re-run; the same lesson the
    crossover scan already learned by saving its raw per-trajectory series.
    """
    out = {}
    per_config = {}
    with torch.no_grad():
        for nx, ny in LOOPS:
            v = (half_retr(plaquette(links)) if (nx, ny) == (1, 1)
                 else half_retr(wilson_loop(links, nx, ny)))
            v = v.mean(dim=(1, 2)).cpu().numpy().astype(float)
            exact = (plaquette_exact(beta, size) if (nx, ny) == (1, 1)
                     else wilson_loop_exact(beta, nx * ny))
            sem = v.std(ddof=1) / math.sqrt(len(v))
            out[f"z_W{nx}x{ny}"] = float((v.mean() - exact) / max(sem, 1e-30))
            out[f"ppm_W{nx}x{ny}"] = float(1e6 * (v.mean() - exact) / exact)
            per_config[f"W{nx}x{ny}"] = v.tolist()
        q = (topological_charge(links).round() ** 2)
        out["q_squared"] = float(q.mean())
        per_config["q_squared"] = q.cpu().numpy().astype(float).tolist()
    out["per_config"] = per_config
    return out


def hmc_ensemble(size, beta, n, device, n_therm_sweeps, n_traj, seed):
    """A fresh HMC start at EXACTLY this coupling.

    Reading the nearest ensemble off disk would be cheaper and wrong: the
    available betas sit 0.3-8% from the chain's values, and a few percent in
    beta moves the observables by more than the effect being measured.
    """
    set_seed(seed)
    action = WilsonU2Action(beta)
    step_size, n_steps = adapted_hmc_params(beta)
    # TOPOLOGICAL UPDATES ON, and with charge_step=1 (the MARGINAL odd move).
    # A cold start with them off is sector-frozen at Q = 0 -- measured, <Q^2> =
    # 0.0000 against an exact 1.64 at L = 32, beta = 63 -- which would make the
    # arms differ in sector content and not only in lift count, and would make
    # the charge-preservation test vacuous by construction.
    hmc = BatchedHMCU2(size, action, n_chains=n, n_steps=n_steps,
                       step_size=step_size, device=device,
                       topological_updates=True, winding_charge_step=1,
                       winding_interval=5)
    links = hmc.initialize(hot=False)
    # heatbath + overrelaxation first: ~7x cheaper than burning in with
    # trajectories, and exact for the same action (see stage 01). retherm_sweeps
    # is that pair; topological_updates stays off, so the sector distribution is
    # whatever the cold start plus HMC produces, which is all this needs -- the
    # arms are compared on LOCAL observables and on charge PRESERVATION, neither
    # of which depends on the start's sector weights.
    links = retherm_sweeps(links, action, n_therm_sweeps)
    for _ in range(n_traj):
        links, _ = hmc.metropolis_step(links)
    return links


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--checkpoint",
                    default="out/u2_2d/checkpoints/det_score_net.pt")
    ap.add_argument("--data-dir", default="out/u2_2d/data_v2")
    ap.add_argument("--start-size", type=int, default=8)
    ap.add_argument("--start-beta", type=float, default=6.4002)
    ap.add_argument("--n-lifts", type=int, default=3)
    ap.add_argument("--n-configs", type=int, default=64)
    ap.add_argument("--sampler-steps", type=int, default=200)
    ap.add_argument("--n-su2", type=int, default=30)
    ap.add_argument("--intermediate-retherm", type=int, default=10,
                    help="retherm sweeps between rungs; 0 = pure model "
                         "composition, which is the contrast that matters")
    ap.add_argument("--final-retherm", type=int, default=10)
    ap.add_argument("--therm-sweeps", type=int, default=60)
    ap.add_argument("--therm-traj", type=int, default=300)
    ap.add_argument("--seed", type=int, default=2626)
    ap.add_argument("--out-dir", default="out/u2_2d/multi_lift")
    args = ap.parse_args()

    device = resolve_device({"device": args.device})
    print(configure_device(device))
    model, sched = load_det_model(args.checkpoint, device=device)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    # ---- the chain of rungs ------------------------------------------------
    rungs = [(args.start_size, args.start_beta)]
    for _ in range(args.n_lifts):
        L, b = rungs[-1]
        rungs.append((L * 2, topology_matched_fine_beta(b, L)))
    print("\nchain:")
    for L, b in rungs:
        print(f"  L={L:3d}  beta={b:10.4f}  model beta={model_beta(b):8.2f}")
    final_size, final_beta = rungs[-1]

    results = []
    for k in range(1, args.n_lifts + 1):
        start_size, start_beta = rungs[args.n_lifts - k]
        print(f"\n{'='*74}\n{k} LIFT(S): start L={start_size} beta={start_beta:.4f}"
              f"  ->  L={final_size} beta={final_beta:.2f}")

        t0 = time.time()
        cache = out / f"hmc_L{start_size}_beta{start_beta:.4f}_topo.pt"
        path = Path(args.data_dir) / f"u2_L{start_size}_beta{start_beta:g}.pt"
        if path.exists():
            links, _ = load_ensemble(path)
            links = links[:args.n_configs].to(device)
            print(f"  start: {path.name} (exact coupling on disk)")
        elif cache.exists():
            # Read the key this script itself writes. `load_ensemble` expects
            # the pipeline's {"configs", "metadata"} layout and raised KeyError
            # on the cache, which is written here as {"links", "meta"}.
            links = torch.load(cache, map_location="cpu")["links"]
            links = links[:args.n_configs].to(device)
            print(f"  start: cached {cache.name}")
        else:
            links = hmc_ensemble(start_size, start_beta, args.n_configs, device,
                                 args.therm_sweeps, args.therm_traj,
                                 args.seed + k)
            torch.save({"links": links.cpu(),
                        "meta": {"beta": start_beta,
                                 "lattice_size": start_size}}, cache)
            print(f"  start: generated by HMC [{time.time()-t0:.0f}s]")

        q_start = topological_charge(links).round().cpu().numpy()
        base = score(links, start_beta, start_size)
        qsq_exact = (start_size ** 2) / (4.0 * math.pi ** 2
                                         * model_beta(start_beta))
        print(f"  start scores: z(plaq)={base['z_W1x1']:+7.2f}  "
              f"<Q^2>={base['q_squared']:.4f} (approx exact {qsq_exact:.3f})")
        if base["q_squared"] < 0.25 * qsq_exact:
            print("  WARNING: start is sector-frozen -- the arms would differ in")
            print("  topology as well as in lift count. Do not read the result.")

        set_seed(args.seed)
        per_rung = []
        for j in range(k):
            L, b = rungs[args.n_lifts - k + j]
            nb = rungs[args.n_lifts - k + j + 1][1]
            ns = L * 2
            links = generate_fine_from_coarse(
                model, sched, links.cpu(), nb, n_su2_sweeps=args.n_su2,
                device=device, n_sampler_steps=args.sampler_steps,
                n_corrector_steps=1, batch_size=32, consistency_weight=1.0,
                physics_blend_coef=0.0).to(device)
            raw = score(links, nb, ns)
            if args.intermediate_retherm and j < k - 1:
                links = retherm_sweeps(links, WilsonU2Action(nb),
                                       args.intermediate_retherm)
            per_rung.append({"lattice_size": ns, "beta": nb,
                             "model_beta": model_beta(nb), "raw": raw})
            print(f"    rung {j+1}: L={ns:3d} beta={nb:9.3f}  "
                  f"z = {raw['z_W1x1']:+8.2f} / {raw['z_W2x2']:+7.2f} / "
                  f"{raw['z_W4x4']:+7.2f}   <Q^2>={raw['q_squared']:.4f}")

        final_raw = score(links, final_beta, final_size)
        post = score(retherm_sweeps(links, WilsonU2Action(final_beta),
                                    args.final_retherm), final_beta, final_size)
        q_end = topological_charge(links).round().cpu().numpy()
        match = float((q_end == q_start).mean())
        print(f"  FINAL raw  z = {final_raw['z_W1x1']:+8.2f} / "
              f"{final_raw['z_W2x2']:+7.2f} / {final_raw['z_W4x4']:+7.2f}")
        print(f"  FINAL +{args.final_retherm} z = {post['z_W1x1']:+8.2f} / "
              f"{post['z_W2x2']:+7.2f} / {post['z_W4x4']:+7.2f}")
        print(f"  charge preserved through {k} lift(s): {100*match:.1f}% "
              f"of configurations")
        results.append({"n_lifts": k, "start_size": start_size,
                        "start_beta": start_beta, "start_score": base,
                        "per_rung": per_rung, "final_raw": final_raw,
                        "final_post": post, "charge_match_fraction": match,
                        "seconds": time.time() - t0})
        save_json(out / f"multi_lift_r{args.intermediate_retherm}.json",
                  {"chain": [{"lattice_size": L, "beta": b,
                              "model_beta": model_beta(b)} for L, b in rungs],
                   "intermediate_retherm": args.intermediate_retherm,
                   "n_configs": args.n_configs, "arms": results})

    # ---- the comparison ----------------------------------------------------
    print(f"\n{'='*74}\nCOMPOUNDING at L={final_size}, beta={final_beta:.2f} "
          f"(model beta {model_beta(final_beta):.1f}), "
          f"intermediate retherm = {args.intermediate_retherm}")
    print(f"  {'lifts':>5s} {'|z| raw W1x1':>13s} {'|z| raw W2x2':>13s} "
          f"{'|z| post W1x1':>14s} {'ppm raw W1x1':>13s} {'Q kept':>8s}")
    for r in results:
        print(f"  {r['n_lifts']:5d} {abs(r['final_raw']['z_W1x1']):13.2f} "
              f"{abs(r['final_raw']['z_W2x2']):13.2f} "
              f"{abs(r['final_post']['z_W1x1']):14.2f} "
              f"{r['final_raw']['ppm_W1x1']:13.1f} "
              f"{100*r['charge_match_fraction']:7.1f}%")

    z1 = abs(results[0]["final_raw"]["z_W1x1"])
    zk = abs(results[-1]["final_raw"]["z_W1x1"])
    print()
    if zk > 2.0 * z1:
        print(f"  ERROR COMPOUNDS: {len(results)} lifts is {zk/max(z1,1e-9):.1f}x "
              f"worse than 1 at the same endpoint.")
        print("  The rung count is a real cost and the ladder should be as short")
        print("  as the base coupling allows.")
    elif zk < 0.5 * z1:
        print(f"  The LONGER ladder is BETTER ({z1/max(zk,1e-9):.1f}x). Not a "
              "compounding effect --")
        print("  check the endpoint's distance to a training rung for each arm's")
        print("  intermediate couplings before reading anything into it.")
    else:
        print(f"  NO COMPOUNDING within resolution: {len(results)} lifts sits at "
              f"{zk/max(z1,1e-9):.2f}x the 1-lift error.")
        print("  Each lift's error is not inherited -- consistent with the tail")
        print("  resetting local structure at every rung while topology, which is")
        print("  transported exactly, cannot degrade at all.")
    print(f"\nwrote {out / 'multi_lift.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
