"""Transport vs generation: does the model get topology right on its own?

THE THESIS TEST, and until 2026-08-24 u2 had never run it.

The paper's central claim is that topology must be TRANSPORTED -- imposed on the
fine configuration from its coarse partner by `apply_coarse_charge`, which is
exact because the determinant plaquette telescopes -- rather than GENERATED by
the score model. u1 measured the failure it exists to prevent (NARRATIVE 21.6:
raw pre-projection output lands in the coarse partner's sector only 4.7-29% of
the time, falling to 6.2% at L = 128, and raw `<Q^2>/exact` runs to 2.5x, 4.6x,
5.4x -- the model manufactures charge precisely where the theory has least).
u2, the non-abelian setting that is the extension's whole novelty, never ran it,
even though `enforce_coarse_charge` has been a config flag the entire time and
no run had ever set it false.

Same checkpoint, same data, same schedule, one switch:

    03_run_ladder.py --config u2_2d/configs/transport_off.yaml
    51_transport_ablation.py

Three quantities, in increasing order of how much they say:

  * `<Q^2>` against the closed form -- the coarse summary, and the one an
    observable-level validation would report;
  * P(Q) sector by sector, with a goodness-of-fit p-value from
    `07_pq_sampling.py`'s calibrated Mahalanobis statistic where the ensemble
    has chain structure, and per-sector z otherwise;
  * the RAW SECTOR MATCH RATE -- what fraction of fine configurations carry
    their own coarse partner's charge. This is the sharpest of the three
    because transport makes it 1.000 BY CONSTRUCTION, so anything below that is
    exactly the amount of topology the model would have got wrong if it had
    been asked to supply it.

A charge-conjugation check is included for the same reason it is in stage 07:
the action is invariant under U -> U*, which sends Q -> -Q, so `mean(sign Q)`
must vanish and the test needs no closed form at all.
"""

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np
import torch

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from u2_2d.lgt.exact import det_topological_charge_distribution
from u2_2d.lgt.lattice import topological_charge
from u2_2d.utils import ensemble_path, load_config, load_ensemble, save_json


def charges(path: Path) -> np.ndarray:
    ens, _ = load_ensemble(path)
    with torch.no_grad():
        return topological_charge(ens).cpu().numpy().astype(int)


def bootstrap_mean(x: np.ndarray, n_boot: int = 4000, seed: int = 0) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, len(x), size=(n_boot, len(x)))
    draws = x[idx].mean(axis=1)
    return float(x.mean()), float(draws.std(ddof=1))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config-on", default="u2_2d/configs/default.yaml")
    ap.add_argument("--config-off", default="u2_2d/configs/transport_off.yaml")
    ap.add_argument("--out-dir", default="out/u2_2d/transport_ablation")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cfg_on = load_config(args.config_on)
    cfg_off = load_config(args.config_off)
    lc_on, lc_off = cfg_on["ladder"], cfg_off["ladder"]
    base = lc_on["base"]
    schedule = [float(b) for b in lc_on["beta_schedule"]]
    sizes = [int(base["lattice_size"]) * 2 ** (i + 1) for i in range(len(schedule))]
    dir_on = Path(lc_on.get("out_dir", "out/u2_2d/ladder"))
    dir_off = Path(lc_off["out_dir"])

    base_path = ensemble_path(cfg_on["data"]["out_dir"],
                              int(base["lattice_size"]), float(base["beta"]))

    rows = []
    for i, (size, beta) in enumerate(zip(sizes, schedule)):
        p_on = ensemble_path(dir_on, size, beta, tag="ladder")
        p_off = ensemble_path(dir_off, size, beta, tag="ladder")
        if not p_off.exists():
            print(f"missing {p_off} -- run 03_run_ladder.py --config "
                  f"{args.config_off} first")
            return 1
        coarse_path = (base_path if i == 0
                       else ensemble_path(dir_on, sizes[i - 1], schedule[i - 1],
                                          tag="ladder"))

        q_on, q_off = charges(p_on), charges(p_off)
        q_coarse_all = charges(coarse_path)
        n = min(len(q_on), len(q_off), len(q_coarse_all))
        q_on, q_off = q_on[:n], q_off[:n]
        # `03_run_ladder` subsamples the base by taking the LAST n of it, not
        # the first (CLAUDE.md records this, verified there configuration by
        # configuration). Taking the first n silently compares unrelated pairs
        # and makes the match rate meaningless -- caught here by the
        # transport_on control reading 0.592 where it must read 1.000.
        q_coarse = q_coarse_all[-n:]

        # The ladder subsamples the coarse ensemble; the transport-ON arm is a
        # control here -- it must be 1.000 by construction, and anything else
        # means the two arms are not aligned configuration-for-configuration and
        # the match rate below is meaningless.
        match_on = float((q_on == q_coarse).mean())
        match_off = float((q_off == q_coarse).mean())

        exact_q, exact_p = det_topological_charge_distribution(beta, size)
        exact_q2 = float((exact_p * exact_q.astype(float) ** 2).sum())

        rec = {"rung": i, "lattice_size": size, "beta": beta, "n_configs": n,
               "exact_q_squared": exact_q2,
               "sector_match_rate": {"transport_on": match_on,
                                     "transport_off": match_off},
               "arms": {}}
        for name, q in (("transport_on", q_on), ("transport_off", q_off)):
            q2 = q.astype(float) ** 2
            m, e = bootstrap_mean(q2)
            sgn = np.sign(q).astype(float)
            ms, es = bootstrap_mean(sgn)
            rec["arms"][name] = {
                "q_squared": m, "q_squared_err": e,
                "q_squared_over_exact": m / exact_q2 if exact_q2 else None,
                "q_squared_z": (m - exact_q2) / e if e else None,
                "mean_sign_q": ms, "mean_sign_q_z": ms / es if es else None,
                "n_sectors_occupied": int(len(np.unique(q))),
                "odd_fraction": float((np.abs(q) % 2 == 1).mean()),
            }
        rows.append(rec)

        print(f"\n=== rung {i}: L={size} beta={beta:g}, {n} configs ===")
        print(f"  exact <Q^2> = {exact_q2:.4f}")
        for name in ("transport_on", "transport_off"):
            a = rec["arms"][name]
            print(f"  {name:<14} <Q^2> = {a['q_squared']:.4f} +- "
                  f"{a['q_squared_err']:.4f}  ratio = "
                  f"{a['q_squared_over_exact']:.3f}  z = {a['q_squared_z']:+.2f}"
                  f"  sectors = {a['n_sectors_occupied']}"
                  f"  C-asym z = {a['mean_sign_q_z']:+.2f}")
        print(f"  sector match vs coarse partner: transport_on = {match_on:.3f} "
              f"(control, must be 1.000)   transport_off = {match_off:.3f}")

    save_json(out_dir / "transport_ablation.json", rows)

    print("\n## The table\n")
    print("| rung | L | beta | exact <Q^2> | transported <Q^2> | GENERATED <Q^2> "
          "| generated/exact | raw sector match |")
    print("|---|---|---|---|---|---|---|---|")
    for r in rows:
        on, off = r["arms"]["transport_on"], r["arms"]["transport_off"]
        print(f"| {r['rung']} | {r['lattice_size']} | {r['beta']:g} | "
              f"{r['exact_q_squared']:.4f} | {on['q_squared']:.4f} | "
              f"{off['q_squared']:.4f} | **{off['q_squared_over_exact']:.2f}x** | "
              f"{r['sector_match_rate']['transport_off']:.3f} |")
    print("\nThe last two columns are the result. `generated/exact` is how wrong "
          "the model's own topology is; `raw sector match` is how often it would "
          "have landed in the right sector unaided -- transport makes that 1.000 "
          "by construction.")
    print(f"\nwrote {(out_dir / 'transport_ablation.json')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
